language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get install libyaml-dev
  - sudo apt-get install cppcheck
  - git clone https://github.com/pfi/pficommon.git
  - pushd pficommon
  - ./waf configure
  - ./waf build
  - sudo ./waf install
  - popd
  - sudo ldconfig
  - rm -rf pficommon
  - wget http://google-styleguide.googlecode.com/svn/trunk/cpplint/cpplint.py
  - chmod +x cpplint.py
  - sudo mv cpplint.py /usr/local/bin

script:
  - ./waf configure --enable-gcov
  - ./waf build --checkall
  - ./waf cpplint
  - cppcheck src/**/*pp

after_success:
  - sudo pip install cpp-coveralls
  - coveralls -b build -r . -E ".*test.cpp" -E ".*gtest.*" -E ".*/usr/.*"  -x .cpp -x .hpp
