language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get install libyaml-dev
  - git clone https://github.com/pfi/pficommon.git
  - pushd pficommon
  - ./waf configure
  - ./waf build
  - sudo ./waf install
  - popd
  - sudo ldconfig
  - wget http://google-styleguide.googlecode.com/svn/trunk/cpplint/cpplint.py
  - chmod +x cpplint.py
  - sudo mv cpplint.py /usr/local/bin

script:
  - ./waf configure
  - ./waf build --checkall
  - ./waf cpplint
